//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace CapaDatos
{
    public partial class Producto
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public long Categoria_ID { get; set; }
    
        public virtual Categoria Categoria { get; set; }

        public List<Producto> GetDBAllProducts()
        {
            List<Producto> lst = new List<Producto>();

            using (NegocioEntities db = new NegocioEntities())
            {
                lst = db.Productoes.ToList();
            }

            return lst;
        }

    }
}
